---
resources:
- name: ci-repo
  type: git
  source:
    uri: https://github.com/gschultzy/test-repo #test repo

- name: ci-project
  type: git
  source:
    uri: https://github.com/gschultzy/ci-project.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: ci-project-web-app
  public: true
  serial: true
  
  plan:
  # Get required resources
  - get: ci-repo
  - get: ci-project
    trigger: true
  # Deploy app to cf
  - put: resource-deploy-web-app
    params:
      manifest: ci-project/manifest.yml
      path: ci-project
  # run unit and integration tests
  - task: web-app-tests
    file: ci-repo/concourse/task_run_tests.yml
    params:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-organization}}
      space: {{cf-space}}