---
resources:
- name: ci-repo
  type: git
  source:
    uri: https://github.com/gschultzy/ci-repo.git

- name: ci-project
  type: git
  source:
    uri: https://github.com/gschultzy/ci-project.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: job-deploy-app
  public: true
  serial: true
  plan:
  - get: ci-repo
  - get: ci-project
    trigger: true
  - task: web-app-tests
    file: ci-repo/concourse/task_run_tests.yml
  - put: resource-deploy-web-app
    params:
      manifest: ci-project/manifest.yml
      path: ci-project
